/* member.js */

export const members = [
    { id: 1, name: '강민하', github: 'm2na7', englishName: 'MinhaKang' },
    { id: 2, name: '고제성', github: 'kojesung', englishName: 'JesungKo' },
    { id: 3, name: '곽서연', github: 'yeonilil', englishName: 'SeoyeonKwak' },
    { id: 4, name: '곽지욱', github: 'gwagjiug', englishName: 'JiugGwag' },
    { id: 5, name: '권동희', github: 'hamxxn', englishName: 'DongheeKwon' },
    { id: 6, name: '권새봄', github: 'kwonsaebom', englishName: 'SaebomKwon' },
    { id: 7, name: '김수연', github: 'mmaybei', englishName: 'SuyeonKim' },
    { id: 8, name: '김시연', github: 'siyeon9302', englishName: 'SiyeonKim' },
    { id: 9, name: '김예원', github: 'yeeeww', englishName: 'YewonKim' },
    { id: 10, name: '김예지', github: 'mnbvcxzyj', englishName: 'YejiKim' },
    { id: 11, name: '김정민', github: 'jjangminii', englishName: 'JeongminKim' },
    { id: 12, name: '김정은', github: 'Jeong-Ag', englishName: 'JeongeunKim' },
    { id: 13, name: '김채은', github: 'bongtta', englishName: 'ChaeeunKim' },
    { id: 14, name: '노민지', github: 'enfantdhiver', englishName: 'MinjiNoh' },
    { id: 15, name: '문혜성', github: 'sndks', englishName: 'HyeseongMoon' },
    { id: 16, name: '박소이', github: 'soyyyyy', englishName: 'SoyPark' },
    { id: 17, name: '박희선', github: 'heesunee', englishName: 'HeesunPark' },
    { id: 18, name: '신지수', github: 'shinjigu', englishName: 'JisuShin' },
    { id: 19, name: '엄경호', github: 'kheee512', englishName: 'KyounghoEom' },
    { id: 20, name: '엄지우', github: '1jiwoo27', englishName: 'JiwooEom' },
    { id: 21, name: '윤소은', github: 'Dubabbi', englishName: 'SoeunYoon' },
    { id: 22, name: '이윤지', github: 'Leeyoonji23', englishName: 'YoonjiLEE' },
    { id: 23, name: '이재림', github: 'jllee000', englishName: 'JaelimLee' },
    { id: 24, name: '이진혁', github: 'constantly-dev', englishName: 'JinHyeokLee' },
    { id: 25, name: '임지성', github: 'jstar000', englishName: 'JisungLim' },
    { id: 26, name: '임지수', github: 'jisooooooooooo', englishName: 'JisooLim' },
    { id: 27, name: '장정훈', github: 'jeonghoon11', englishName: 'JeonghoonJang' },
    { id: 28, name: '정희연', github: 'heeyyeon', englishName: 'HeeyeonJung' },
    { id: 29, name: '조성하', github: 'earl9rey', englishName: 'SunghaCho' },
    { id: 30, name: '조혜린', github: 'jogpfls', englishName: 'HyerinCho' },
    { id: 31, name: '최서희', github: 'karnelll', englishName: 'SeoheeChoi' },
    { id: 32, name: '한수정', github: 'hansoojeongsj', englishName: 'SoojeongHan' },
    { id: 33, name: '한승우', github: 'seungwoohan12', englishName: 'SeungwooHan' },
    { id: 34, name: '황인영', github: 'hwiy01', englishName: 'InYoungHwang' },
    ];
    